inherit_from:
  - vendor/hound/config/style_guides/ruby.yml
  - .rubocop_todo.yml

# Rails cops
AllCops:
  RunRailsCops: true

# Files you want to exclude
AllCops:
  Exclude:
    - db/schema.rb
    - tmp/aruba/Guardfile
    - tmp/aruba/Gemfile

# TODO: put your overrides here:
