rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ree
  - jruby
  - rbx-1.2.4
  - rbx
branches:
  only:
    - master
    - dev
env:
  - GUARD_SLEEP=1
notifications:
  recipients:
    - thibaud@thibaud.me
    - rymai@rymai.me
    - michi@netzpiraten.ch
    - yann.lugrin@sans-savoir.net
  irc: "irc.freenode.org#guard"
