language: ruby
bundler_args: --without development
rvm:
  - 1.9.3
  - 2.0.0
  - jruby-19mode
  - rbx-19mode
  - 2.1.0-preview2
matrix:
  allow_failures:
    - rvm: rbx-19mode
    - rvm: 2.1.0-preview2
notifications:
  recipients:
    - thibaud@thibaud.me
    - remy@rymai.me
    - michi@netzpiraten.ch
  irc: 'irc.freenode.org#guard'
  webhooks: https://www.buildheroes.com/api/projects/870763b3173212e1df41d8825927256e18bbaba1/builds
