language: ruby
bundler_args: --without development
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.2
  - jruby
  - rbx
matrix:
  allow_failures:
    - rvm: rbx
    - rvm: jruby
notifications:
  recipients:
    - thibaud@thibaud.gg
  irc: 'irc.freenode.org#guard'
