rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ruby-head
  - ree
  - jruby-18mode
  - jruby-19mode
  - jruby-head
  - rbx-18mode
  - rbx-19mode
bundler_args: --without=development
branches:
  only:
    - master
env:
  - GUARD_SLEEP=1
notifications:
  recipients:
    - thibaud@thibaud.me
    - rymai@rymai.me
    - michi@netzpiraten.ch
    - yann.lugrin@sans-savoir.net
  irc: "irc.freenode.org#guard"
