language: ruby
bundler_args: --without development
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.2
  - jruby
  - rbx
matrix:
  allow_failures:
    - rvm: rbx
    - rvm: jruby
notifications:
  recipients:
    - thibaud@thibaud.gg
    - remy@rymai.me
    - michi@flinkfinger.com
  irc: 'irc.freenode.org#guard'
  webhooks: https://www.buildheroes.com/api/projects/870763b3173212e1df41d8825927256e18bbaba1/builds
